### ISSUE TITLE
Version not compatible with Latest IntelliJ version

### ISSUE THREAD

**Issue by Alonski** [patricklx/intellij-emberjs-experimental#101]
### Description

Wanted to update Webstorm to v2023.3 and get a warning that `Plugin incompatible with the new build found: Ember Experimental.js`

Thanks for all the hard work on this!

**Comment by SanderKnauff** [comment]
I just downloaded Webstorm v2023.3 and to me it seems to be working. What version is your plugin reporting?

**Comment by patricklx** [comment]
this should be working, probably didnt update to latest plugin version.
