### ISSUE TITLE
TemplateOnlyComponent parameters are not recognized in GTS files

### ISSUE THREAD

**Issue by SanderKnauff** [patricklx/intellij-emberjs-experimental#104]
### Description

When creating a typed TemplateOnlyComponent in a GTS file, Intellij will not recognize the component parameters.
`<template>` blocks in class components seem fine.

### Steps to Reproduce

1. Clone https://github.com/universal-ember/ember-primitives
2. Open `./ember-primitives/src/components/avatar.gts`

**Expected behavior:**

Component parameters that are described in the Signature should be properly resolved. 

**Actual behavior:**

Any use of `@param` in an TemplateOnlyComponent will yield an "Unresolved symbol" error.

**Reproduces how often:**

This can always be reproduced.

### Versions

IntelliJ IDEA 2023.3.2 RC (Ultimate Edition)
Build #IU-233.13135.65, built on December 14, 2023

### Additional Information

Doing the same in VSCode works fine. Does it use the same LSP?

**Comment by SanderKnauff** [comment]
Thank you. I can confirm this is working on the latest version (I build it from source as the update was not available yet at time of testing)

**Comment by patricklx** [comment]
Yeah, a lot is broken because of an internal change to intelij lsp classes.
Now I'm not getting any references from glint :(
I will try to implement what i can with intellij own psi references... The only parts i cannot resolve are things that contain typescript with type parameters
