### ISSUE TITLE
GTS: imports to GTS files are reporting as unresolved

### ISSUE THREAD

**Issue by SanderKnauff** [patricklx/intellij-emberjs-experimental#108]
### Description

When importing from a GTS file, IntelliJ reports the import as unresolvable.
This also causes the imported values to not have their types known.

### Steps to Reproduce

1. Clone https://github.com/universal-ember/ember-primitives
2. Open `./ember-primitives/src/components/popover.gts`

**Expected behavior:**

The imports `import { Portal } from './portal';` and `import { TARGETS } from './portal-targets';` should resolve.
The `Portal` and `TARGETS` should have intellisense.

**Actual behavior:**

IntelliJ shows the import as unresolved.
The values act as if they have a type of `unknown`

**Reproduces how often:**

This can always be reproduced

### Versions

IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023

Plugin version: 2023.3.1

**Comment by patricklx** [comment]
Glint References are fixed. But the imports are still marked red.
I know why, but needs more work
