### ISSUE TITLE
GTS: imported components show as unused

### ISSUE THREAD

**Issue by SanderKnauff** [patricklx/intellij-emberjs-experimental#109]
### Description

When importing from a GTS file, IntelliJ reports the import as unresolvable.
This also causes the imported values to not have their types known.

### Steps to Reproduce

1. Clone https://github.com/universal-ember/ember-primitives
2. Open `./ember-primitives/src/components/popover.gts`

**Expected behavior:**

The import `import { Velcro } from 'ember-velcro';` should show as used, as it is used in the component template at line 216.

**Actual behavior:**

The import `import { Velcro } from 'ember-velcro';` shows as unused

**Reproduces how often:**

This can always be reproduced

### Versions

IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023

Plugin version: 2023.3.1

### Additional Information

The fields on the `|velcro|` value yielded from the `<Velcro>` component also are unresolved, could this be related to the issue itself or should this be considered to be another bug?

**Comment by patricklx** [comment]
It is probably related.  Or it's an issue with intellij lsp not giving me any references anymore...
When you ctrl+click on the <Velcro tag, does it jump to the definition or import?

**Comment by SanderKnauff** [comment]
> It is probably related. Or it's an issue with intellij lsp not giving me any references anymore... When you ctrl+click on the <Velcro tag, does it jump to the definition or import?

When I ctrl + click on the tag, the editor jumps to the import. That part seems to be working correctly
