### ISSUE TITLE
GTS: Type from yielded value of `let` is unknown

### ISSUE THREAD

**Issue by SanderKnauff** [patricklx/intellij-emberjs-experimental#111]
### Description

When using `{{#let}} in a GTS template, the yielded value is `unknown`

### Steps to Reproduce

1. Clone https://github.com/universal-ember/ember-primitives
2. Open `./ember-primitives/src/components/avatar.gts`

**Expected behavior:**

The attributes on `imgState`, which is yielded from `{{#let (ReactiveImage @src) as |imgState|}}` on line 80, can be found and used.

**Actual behavior:**

The attributes on `imgState` are reported as unresolved.

IntelliJ shows the import as unused

**Reproduces how often:**

This can always be reproduced

### Versions

IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023

Plugin version: 2023.3.1

**Comment by patricklx** [comment]
fixed by #112
