### ISSUE TITLE
IntelliJ Platfrom API change in 2024.1: Lsp4jUtilKt.convertMarkupContentToHtml(...) removed

### ISSUE THREAD

**Issue by alexander-doroshko** [patricklx/intellij-emberjs-experimental#131]
Hi from JetBrains,

Just wanted to let you know that the `Lsp4jUtilKt.convertMarkupContentToHtml(...)` function is going to be removed in 2024.1. 

I see it's used in `GlintTypeScriptService.createQuickInfoResponse()`. The fix is as easy as removing the `GlintTypeScriptService.createQuickInfoResponse(...)` overriding function. In 2024.1, the base function `BaseLspTypeScriptService.createQuickInfoResponse(...)` will work just fine.

**Comment by Alonski** [comment]
Can we please get a new release with this 😄 
I know this is hard and thankless work so thank you so much for this!

**Comment by SergeAstapov** [comment]
looks like new version is not yet available on https://plugins.jetbrains.com/plugin/15499-ember-experimental-js, was there some missing step in publishing?

btw Big Thank you for this plugin!

**Comment by patricklx** [comment]
> looks like new version is not yet available on https://plugins.jetbrains.com/plugin/15499-ember-experimental-js, was there some missing step in publishing?
> 
> btw Big Thank you for this plugin!

No, it was published correctly. Just need to wait for jetbrains review
