### ISSUE TITLE
Using new release and getting this now: element.text must not be null

### ISSUE THREAD

**Issue by robclancy** [patricklx/intellij-emberjs-experimental#16]
Using new release I have a new error.

> In file: file:///home/robbo/Code/postedin/app/resources/assets/app/components/workflow/planning/plan.hbs
> 
> java.lang.NullPointerException: element.text must not be null
> 	at com.emberjs.utils.EmberUtils$Companion.handleEmberHelpers(EmberUtils.kt:424)
> 	at com.emberjs.utils.EmberUtils$Companion.followReferences(EmberUtils.kt:266)
> 	at com.emberjs.utils.EmberUtils$Companion.followReferences(EmberUtils.kt:298)
> 	at com.emberjs.utils.EmberUtils$Companion.followReferences$default(EmberUtils.kt:249)
> 	at com.emberjs.utils.EmberUtils$Companion.getComponentReferenceData(EmberUtils.kt:598)
> 	at com.emberjs.EmberXmlElementDescriptor.getReferenceData(EmberXmlElementDescriptor.kt:102)
> 	at com.emberjs.EmberXmlElementDescriptor.getAttributesDescriptors(EmberXmlElementDescriptor.kt:122)
> 	at com.emberjs.EmberXmlElementDescriptor.getAttributeDescriptor(EmberXmlElementDescriptor.kt:153)
> 	at com.emberjs.EmberXmlElementDescriptor.getAttributeDescriptor(EmberXmlElementDescriptor.kt:158)
> 	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptionImpl(XmlAttributeDelegate.java:68)
> 	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.lambda$getDescriptor$0(XmlAttributeDelegate.java:55)
> 	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
> 	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
> 	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
> 	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
> 	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
> 	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
> 	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
> 	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
> 	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
> 	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
> 	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
> 	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
> 	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
> 	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptor(XmlAttributeDelegate.java:53)
> 	at com.intellij.psi.impl.source.xml.XmlAttributeImpl.getDescriptor(XmlAttributeImpl.java:191)
> 	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.checkAttribute(XmlHighlightVisitor.java:308)
> 	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.visitXmlToken(XmlHighlightVisitor.java:95)
> 	at com.intellij.psi.impl.source.xml.XmlTokenImpl.accept(XmlTokenImpl.java:29)
> 	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.visit(XmlHighlightVisitor.java:596)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:347)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:285)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:309)
> 	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:606)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:309)
> 	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:276)
> 	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:221)
> 	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
> 	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
> 	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
>

**Comment by patricklx** [comment]
which version do you have? that looks some older. current version is v2022.2.31

**Comment by robclancy** [comment]
I downloaded the latest release and installed from disk, maybe it messed up then.

**Comment by robclancy** [comment]
Yeah I tried the version here https://github.com/patricklx/intellij-emberjs-experimental/issues/15#issuecomment-1257789653
