### ISSUE TITLE
Constant reindexing of the open file

### ISSUE THREAD

**Issue by vlascik** [patricklx/intellij-emberjs-experimental#17]
First of all, thank you for this fork, it's awesome & so much better than the original. Especially love the Glint support.

However just updated the IDEA and the plugin, and I'm experiencing several issues.

Starting I think v2022.2.36 and in .37, currently open file is getting reindexed constantly in every open project, which spikes the CPU and renders the IDE unusable.

In v2022.2.26 - 29 Glint works, but throws exceptions. v2022.2.30 doesn't do Glint completions at all.

Last version that works properly, without reindexing, exceptions and with Glint, is v2022.2.25.

Not sure how I can describe what's happening better, but let me know if there's anything I can do to help track it down.

Thank you.

Win10, IDEA Ultimate 2022.2.3.

**Comment by patricklx** [comment]
So it's only reindexing the open file and not he whole project? One change i did was indeed recreating the PSI after a project indexing completed. I did it to update the references and completions which depend on the index, but are cached by intellij.
I guess i have to rethink how to achieve it

**Comment by patricklx** [comment]
Not sure about the glint issue. Msybe it's also related to the indexing issue

**Comment by patricklx** [comment]
It's strange that it fails from 29 to 30... The only change was to add glint annotation to hbs string tags in js/ts

**Comment by patricklx** [comment]
Did you test the different versions with same code? Does glint work in vscode?
