### ISSUE TITLE
Plugin incompatible with IDEA 2012.3

### ISSUE THREAD

**Issue by ksrb** [patricklx/intellij-emberjs-experimental#2]
### Description
This plugin is incompatible with the latest IntelliJ Ultimate Edition any chance on an update?

![image](https://user-images.githubusercontent.com/3750409/144311403-47c6f088-f348-4ccd-b5f5-0408caa30514.png)

### Versions

IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
macOS 11.6.1

**Comment by patricklx** [comment]
should be up in the next days
