### ISSUE TITLE
How does this plugin relate to Turbo87/intellij-emberjs?

### ISSUE THREAD

**Issue by XuluWarrior** [patricklx/intellij-emberjs-experimental#20]
Does this have everything thing that [Turbo87/intellij-emberjs](https://github.com/Turbo87/intellij-emberjs) has plus extra features?
Or do the two projects diverge in different ways?

I suppose my real question is, do I lose anything moving to "experimental"?  Does "experimental" mean that there is stuff more likely to break?

**Comment by patricklx** [comment]
Hi, It's a fork of Turbo87/intellij-emberjs, with additional features. But yes, it means it's likely to break when i introduce new features or when i support a new intellij version. Although i also fix issues fast.

**Comment by XuluWarrior** [comment]
Turbo87/intellij-emberjs looks like it is still actively developed.
Do you ensure that your fork keeps up to date with changes there?  Or is there a chance of new stuff (or fixes) appearing there but not here?

**Comment by patricklx** [comment]
Right, i sync it sometimes. But no fixed schedule.
Most often when upgrading to newer intellij version
