### ISSUE TITLE
Update for intellij 2023.2.0

### ISSUE THREAD

**Issue by cah-brian-gantzler** [patricklx/intellij-emberjs-experimental#32]
Thanks for all the hard work. Seems I updated intellij to 2023.2.0 before checking if this plugin had ben updated. 

When you get a chance to make it compatible, thanks

**Comment by patricklx** [comment]
fixed by https://github.com/patricklx/intellij-emberjs-experimental/commit/a4b185df750091d5734a22ac789a324c2d8bd77f

**Comment by cah-brian-gantzler** [comment]
Thanks, didnt expect so much code to bump a version. Or were there some features added?

**Comment by patricklx** [comment]
yeah, lsp support is still internal & private code, so it can change any time.
I read somewhere that they are moving it soon to public, so after that this should be easier :)

**Comment by cah-brian-gantzler** [comment]
You talking about this  https://youtrack.jetbrains.com/issue/IDEA-162901/Provide-LSP-API-for-external-plugin-developers#focus=Comments-27-7613792.0-0? Cause it looks like this release. Tried to update plugins, dont see this yet. Let me know when I can update. Trying to use the new template code and getting no syntax highlighting as the plugin is disabled for 2023.2.0

**Comment by patricklx** [comment]
ah, right. but its still marked as experimental...
sure, it's gonna take a while, a few hours to 1 day until intellij approves the update

**Comment by patricklx** [comment]
It's now available: https://plugins.jetbrains.com/plugin/15499-ember-experimental-js/versions/stable/370882🚀

**Comment by cah-brian-gantzler** [comment]
Great, I have syntax highlighting again.

FYI, not sure if this is you or Intellij, but hash when imported and used always reports as an unused import

**Comment by patricklx** [comment]
you mean this?
```js
import { hash } from "@ember/helper";
```
which is working for me when used.
can you provide an example?

**Comment by cah-brian-gantzler** [comment]
<img width="812" alt="image" src="https://github.com/patricklx/intellij-emberjs-experimental/assets/1529286/8a5b8d2e-ae87-43ed-8a8d-d8eac86ecd9b">

Hmmm, another person is seeing `on` the same way. Note we are js still, trying to get to typescript but having some addons clashing typescript versions when trying to add it to the project.  

Did screen shot so you could see the hash import was grey

```
// Template imports
import { LinkTo } from '@ember/routing';
import { hash } from '@ember/helper';

<template>
  <div class='panel panel-default' ...attributes>
    <div class='panel-heading'>
      <h3 class='panel-title' data-test-title>{{@title}}</h3>
    </div>
    <div class='list-group' data-test-menu-group>
      {{#each @items as |item|}}
        {{#unless item.hide}}
          <LinkTo
            class='list-group-item'
            data-test-menu-item
            data-test-id={{item.dataTestId}}
            @route={{item.route}}
            @query={{if item.query item.query (hash)}}
          >{{item.description}}</LinkTo>
        {{/unless}}
      {{/each}}
    </div>
  </div>
</template>
```

**Comment by patricklx** [comment]
i created an issue for it.
https://github.com/patricklx/intellij-emberjs-experimental/issues/45
i think i have a better implementation for it now. will publish it soon

**Comment by patricklx** [comment]
@cah-brian-gantzler is this fixed for you now?
