### ISSUE TITLE
imports sometimes marked as unused

### ISSUE THREAD

**Issue by patricklx** [patricklx/intellij-emberjs-experimental#45]

**Comment by patricklx** [comment]
@cah-brian-gantzler is this fixed for you now?

**Comment by cah-brian-gantzler** [comment]
Updated to 1.54 and at first I thought it was working, the import was white, but after a few seconds, it went grey again. Also checked the other component we have done (is has the on modifier) and that was still grey a well

**Comment by cah-brian-gantzler** [comment]
Updated to 1.55 and it does appear to be working as expected. Thanks
