### ISSUE TITLE
trailing commas on hashes are marked as not needed

### ISSUE THREAD

**Issue by cah-brian-gantzler** [patricklx/intellij-emberjs-experimental#54]
### Description

Intellij marks trailing commas on hashes as unneeded on gjs files but not on js files. I have prettier adding these (might be part of the default, not sure)

### Steps to Reproduce

Add any hash to a gjs file and leave the trailing comma on the last item

**Expected behavior:** Commas on final item of hash should not be marked as unneeded

**Actual behavior:** Commas on final item of has are marked as unneeded

**Reproduces how often:** Always

### Versions

- The first two lines of the `Help` -> `About` output:

IntelliJ IDEA 2023.2.0 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`):

2023.1.55 

### Additional Information

Assuming the new file type that is registered in Intellij of gjs is not having the correct linting for the comma thing applied.

**Comment by patricklx** [comment]
Is the error an eslint error or fron intellij itself?

**Comment by patricklx** [comment]
Ah, you mean the style you set in intellij for js/ts files is not applied to gjs/gts?

**Comment by cah-brian-gantzler** [comment]
I have no idea, just putting guesses in. 

Its in the intellij editor, whatever linting the editor is applying. 

Here is a gjs file
![image](https://github.com/patricklx/intellij-emberjs-experimental/assets/1529286/0929dce0-b9dd-4632-ad5a-5d07751cbc8b)

here is a js file
![image](https://github.com/patricklx/intellij-emberjs-experimental/assets/1529286/82a85eca-307e-463e-a257-6e33c70f6c6d)

**Comment by cah-brian-gantzler** [comment]
Confirmed has been fixed. Thanks
