### ISSUE TITLE
Helpers invoked with parens do not mark imports as used and have a linting error

### ISSUE THREAD

**Issue by cah-brian-gantzler** [patricklx/intellij-emberjs-experimental#60]
### Description

imports not marked as used when they are helpers with no params
invocation of helpers with no params are marked as a linting issue

### Steps to Reproduce
Use a helper with no params in a test. `noop` from ember composable helpers is a good one.  When a helper has no params, you must enclose it in parens to invoke it, else the object is passed. 

![image](https://github.com/patricklx/intellij-emberjs-experimental/assets/1529286/103121af-a615-4725-9957-de8159938d26)

![image](https://github.com/patricklx/intellij-emberjs-experimental/assets/1529286/ce30d370-5ad3-439a-99cd-b4d7a767f00e)

In this case, `optional null` actually does the same thing, but it shows the behaviour. `Optional` is marked as a used import, `noop` is not. `Optional` does not have a linting error, `noop` does. 

If you invoke the `optional` with the parens, while still valid, has the linting error. 
![image](https://github.com/patricklx/intellij-emberjs-experimental/assets/1529286/bd681bd1-70fe-4b7c-ace5-f0a202ec16e7)

**Comment by patricklx** [comment]
the linting errors are an issue with the handlebars parser from intellij. it cannot parse it correctly... though I know its beeing used recently in emberjs....
because it fails to parse that part, it also cannot detect its usage.
I can try to fix this in intellij handlbars

**Comment by patricklx** [comment]
https://github.com/JetBrains/intellij-plugins/pull/895

**Comment by cah-brian-gantzler** [comment]
Thanks for doing that

**Comment by patricklx** [comment]
fixedd in https://github.com/JetBrains/intellij-plugins/commit/2ed1ea63788977c6891f0b333a014be594ec5d1b

**Comment by cah-brian-gantzler** [comment]
Thanks. Thats awesome. Ill try it out
