### ISSUE TITLE
javascript unresolved symbol in templates

### ISSUE THREAD

**Issue by cah-brian-gantzler** [patricklx/intellij-emberjs-experimental#71]
### Description

For javascript (I assume this is not a problem for typescript), most the properties in a template are marked as unresolved. This puts the red squigglies  underneath and marks as possible errors and marking all the files as possible problems. 

I dont know if this is coming from this addon, but if the file is gjs, could it be possible not to mark the unresolved?  

From the screen shot you can see all the passed in params (starting with @) are marked unresolved. Any yielded variables, the props on them, etc. You can also see in the list of files, that all files are marked as possible problems. Hard to know where the real problems are. 

![image](https://github.com/patricklx/intellij-emberjs-experimental/assets/1529286/2de462e8-9de2-4e2f-8b41-5ce54845cbe4)

**Comment by patricklx** [comment]
Ah, right. I need to disable the template linter for gjs
