### ISSUE TITLE
Can't create a new Ember file from WebStorm "Generate Ember.js Files" window.

### ISSUE THREAD

**Issue by jahrock** [patricklx/intellij-emberjs-experimental#81]
### Description

Can't create a new Ember file from WebStorm "Generate Ember.js Files" window.

### Steps to Reproduce

Initial steps to open "Ember.js Files" window: File -> New -> Ember.js Files
Input name: hacktoberfest
Select kind: Route or any other option

**Expected behavior:** A successfully created new Ember route file.

**Actual behavior:** A error message is shown.
```
Problem running ember-cli:
Process did not exit properly (code = 127). Please try again on the command line.
```

**Reproduces how often:** 100%

### Versions

- The first two lines of the `Help` -> `About` output:
WebStorm 2023.2.2
Build #WS-232.9921.42, built on September 12, 2023

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`):
WebStorm 2023.2.6

- The version of `OS`
Ubuntu 23.04

### Additional Information

I could reproduce the issue with any kind of ember file type, e.g. `Route`, `Controller`, `Serializer`.

**Comment by patricklx** [comment]
does `ember generate route hacktoberfest` work?

**Comment by jahrock** [comment]
Yes it does work.

```
$ ember generate route hacktoberfest
installing route
installing route-test
```

**Comment by jahrock** [comment]
```
$ ember -v
ember-cli: 4.8.0
node: 18.15.0
os: linux x64
```

**Comment by patricklx** [comment]
127 exit code normally means that some command could not be found.
the command intellij actually runs is
`./node_modules/.bin/ember` 
does it exists?

**Comment by jahrock** [comment]
I assumed that creating a new file works the same way as creating a new project with `New Project` window.

Just to clarify, it works as expected if I run `ember`, `./node_modules/.bin/ember` or `./node_modules/ember-cli/bin/ember`
```
$ ./node_modules/.bin/ember g service hacktoberfest
installing service
  create app/services/hacktoberfest.js
installing service-test
  create tests/unit/services/hacktoberfest-test.js

```
