### ISSUE TITLE
Issue with Ember Intl

### ISSUE THREAD

**Issue by Eredrim** [patricklx/intellij-emberjs-experimental#82]
### Description

With Ember Intl 5.x and 6.x, translation placeholder displays "Missing translation: key.to.translation"

### Steps to Reproduce
Create a new ember app with ember Intl 5.x or 6.x. Fill in config/ember-intl.js with your own settings.

**Expected behavior:** This configuration should be sufficient to display translation placeholders in hbs

**Actual behavior:** translation placeholder displays "Missing translation: key.to.translation"

**Reproduces how often:** 100%

### Versions

- The first two lines of the `Help` -> `About` output:

IntelliJ IDEA 2023.1.4 (Ultimate Edition)
Build #IU-231.9295.16, built on July 12, 2023

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`): 2023.1.52

### Additional Information

The IDEA module should read `includeLocales` setting to find the right translation file. Instead of that, module reads `baseLocale` setting (that doesn't exist anymore since Ember intl 5.x). So hbs placeholders are not rightly displayed.

**Comment by patricklx** [comment]
one thing to make sure.
It should fall back automatically to 'en' or 'en-us'. So you do not have those languages?

**Comment by Eredrim** [comment]
> one thing to make sure. It should fall back automatically to 'en' or 'en-us'. So you do not have those languages?

It did not with the new versions of Ember-intl, but indeed fallback worked in versions < 5.x.
Anyway, thanks for your update 👍. I'm looking forward for testing that.
