### ISSUE TITLE
Show Ember Template Lint Errors in Script Files?

### ISSUE THREAD

**Issue by Alonski** [patricklx/intellij-emberjs-experimental#90]
### Description

Is it possible to setup error tracking in Script files such as TS,JS,GTS,GJS files?

I want errors to be underlined in templates inside script files such as hbs invocation or `<template>` tags in GTS files.

What do you think?

**Comment by patricklx** [comment]
Should be easy to do.
There is also https://github.com/patricklx/eslint-plugin-ember-template-lint
